### PR TITLE
fix: default in Vue instance for module federation in mjs file

### PR DESCRIPTION
**Pull request by philgruneich**
Checking for the default key in Vue so it works with module federation: https://github.com/vueuse/vue-demi/issues/130

### CODE REVIEW

**Comment by stheart76** [comment]
When are you merged into Master?

**Comment by antfu** [comment]
Thanks, but no `vue-demi` will default to Vue 3. If you want to force import Vue 2 you can import from `vue-demi/lib/v2/index.mjs`

**Comment by stheart76** [comment]
thank you. But we use module federation in webpack 5.
If vue is shared, when you import vue, vue components are in vue.default.
therefore. https://github.com/vueuse/vue-demi/pull/131/commits/84fd0ff33a5c67f53020fac816722726ab68febd
I hope lib/index.mjs here is applied.

**Comment by wxpwxpwxp** [comment]
i think the error caused by webpack, should not fix it here, open issue(https://github.com/webpack/webpack/issues/16000)

**Comment by mtxue97** [comment]
> thank you. But we use module federation in webpack 5. If vue is shared, when you import vue, vue components are in vue.default. therefore. [84fd0ff](https://github.com/vueuse/vue-demi/commit/84fd0ff33a5c67f53020fac816722726ab68febd) I hope lib/index.mjs here is applied.

same problem 😟

**Pull request closed without merging**
